---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=newapp.conf dest=/etc/init/newapp.conf

# - name: Start gunicorn Upstart Job
#   sudo: yes
#   service: name=bookapp state=restarted
